{
  imports = [
    ./auditd.nix
    ./drawio.nix
    ./email.nix
    ./faillock.nix
    ./files.nix
    ./flatpak.nix
    ./fonts.nix
    ./hardening.nix
    ./keyring.nix
    ./journald.nix
    ./networking.nix
    ./nix.nix
    ./packages.nix
    ./tasks.nix
    ./users.nix
    #../common/systemd-hardening.nix
    ./virtualization.nix
    ./time.nix
    ./usbguard.nix
    ./wayland.nix
    ./wireguard.nix
    ./yubikey.nix
  ];
}
