{
  imports = [
    ./drawio.nix
    ./email.nix
    ./files.nix
    ./flatpak.nix
    ./fonts.nix
    ./hardening.nix
    ./keyring.nix
    ./journald.nix
    ./networking.nix
    ./nix.nix
    #./systemd-hardening.nix
    ./virtualization.nix
    ./time.nix
    ./usbguard.nix
    ./wayland.nix
    ./wireguard.nix
    ./yubikey.nix
  ];
}
