# @desc: Cross-platform user CLI packages
{...}: {
  flake.modules.homeManager.cliPackages = {pkgs, ...}: {
    home.packages = with pkgs; [
      age
      ansible
      asciinema
      bat
      btop
      cilium-cli
      delta
      dig
      distrobox
      duf
      dust
      eza
      fastfetch
      ffmpeg
      fluxcd
      fortune
      fzf
      go-task
      hexyl
      imagemagick
      just
      jq
      ktop
      kubeconform
      kubectl
      kubernetes-helm
      lazygit
      lua-language-server
      marksman
      nil
      nixd
      nix-tree
      pre-commit
      ripgrep
      ripgrep-all
      rustscan
      shellcheck
      sops
      talosctl
      tealdeer
      usbutils
      watchexec
      yaml-language-server
      yazi
      yq-go
    ];
  };
}
