# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "uas" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ "dm-snapshot" "cryptd" ];
  boot.initrd.luks.devices."cryptroot".device = "/dev/disk/by-uuid/9483ae9d-db6a-4cb6-bf80-1e8d5e7e29fe";
  boot.kernelModules = [ "kvm-amd" ];

  # Fix screen flickering and hopefully fix random AMD GPU freezes
  boot.kernelParams = [
    # Disable Scatter/Gather display
    "amdgpu.sg_display=0"

    # Disable panel self-refresh
    "amdgpu.dcdebugmask=0x10"

    # Disable Adaptive Backlight Management
    "amdgpu.abm_level=0"
  ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/98507d22-b738-4c90-ab75-a782aed01d0f";
      fsType = "btrfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/9A11-D13D";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

#  swapDevices =
#    [ { device = "/dev/disk/by-label/NIXOS_SWAP"; }
#    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.enableAllFirmware = true;
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
