# https://starship.rs/config/
# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

format = '$all$username$hostname:$directory$character'
right_format = '$kubernetes@$time'

[directory]
format= '[$path]($style)[$read_only]($read_only_style) '
style = 'white bold'

[username]
style_user = 'green bold'
style_root = 'white bold'
format = '[$user@]($style)'
disabled = false
show_always = true

[git_commit]
disabled = true

[git_branch]
disabled = true

[git_state]
disabled = true

[git_metrics]
disabled = true

[git_status]
disabled = true

[hostname]
ssh_only = false
format = '[$hostname](green)'
disabled = false

[cmd_duration]
disabled = true

[character]
success_symbol = '[%]($white bold)'
error_symbol = '[%]($white bold)'

[time]
disabled = false
format = '[$time](white) '
time_format = '%T'
utc_time_offset = '-5'
#time_range = ''

[kubernetes]
format = '($cluster)'
disabled = false
contexts = [
  { context_pattern = "dev.local.cluster.k8s", style = "green", symbol = "💔 " },
]

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true
# ~/.config/starship.toml

[aws]
disabled = true
